feature/PI-279-prevent_ref_sandbox added quick fail for ref sandbox

diff --git a/.github/workflows/deploy-nonprod-workspace.yml b/.github/workflows/deploy-nonprod-workspace.yml
--- a/.github/workflows/deploy-nonprod-workspace.yml
+++ b/.github/workflows/deploy-nonprod-workspace.yml
@@ -19,6 +19,16 @@ on:
         default: false
 
 jobs:
+  check-for-ref-sandbox:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Reject if ref sandbox
+        run: |
+          if [[ "${{ inputs.account }}" == "ref" && "${{ inputs.sandbox }}" == "true" ]]; then
+            echo "Error: Sandbox deployment is not allowed for the 'ref' account."
+            exit 1
+          fi
+
   deploy:
     uses: ./.github/workflows/_deploy.yml
     with:
